openapi: "3.0.1"
info:
  version: "1.0"
  title: OEP getInstance (reverse engineered API)
paths:
  /getinstances/family/{familyId}:
    get:
      summary: List all flowInstances for the provided dates
      tags:
        - getInstance
      parameters:
      - name: familyId
        in: path
        description: Family ID
        required: true
        schema:
          type: string
        example: 170
      - name: fromDate
        in: query
        schema:
          type: string
          format: date
        description: The fromDate
      - name: toDate
        in: query
        schema:
          type: string
          format: date
        description: The toDate
      responses:
        200:
          description: An array of flowInstances
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlowInstance"
components:
  schemas:
    FlowInstance: 
      type: object
      properties: 
        flowInstanceID: 
          type: integer
          format: int32
        added: 
          type: string
        firstSubmitted: 
          type: string
        fullyPopulated: 
          type: boolean
        stepID: 
          type: integer
          format: int32
        lastStatusChange: 
          type: string
        profileID: 
          type: integer
          format: int32
        userDescription: 
          type: string
        managerDescription: 
          type: string
        remote: 
          type: boolean
        addedInMilliseconds: 
          type: integer
          format: int64
        firstSubmittedInMilliseconds: 
          type: integer
          format: int64
        lastStatusChangeInMilliseconds: 
          type: integer
          format: int64
        poster: 
          type: object
          properties: 
            user: 
              type: object
              properties: 
                userID: 
                  type: integer
                  format: int32
                username: 
                  type: string
                firstname: 
                  type: string
                lastname: 
                  type: string
                email: 
                  type: string
                admin: 
                  type: boolean
                enabled: 
                  type: boolean
                lastLogin: 
                  type: string
                lastLoginInMilliseconds: 
                  type: integer
                  format: int64
                added: 
                  type: string
                isMutable: 
                  type: boolean
                hasFormProvider: 
                  type: boolean
