openapi: "3.0.1"
info:
  version: "1.0"
  title: OEP getInstance (reverse engineered API)
paths:
  /getinstance/{flowInstanceId}/xml:
    get:
      summary: Get flowInstance for the provided flowInstanceId
      tags:
        - getInstance
      parameters:
      - name: flowInstanceId
        in: path
        description: FlowInstanceID
        required: true
        schema:
          type: string
        example: 5744
      responses:
        200:
          description: A flowInstance
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/FlowInstance"
components:
  schemas:
    FlowInstance: 
      type: object
      properties: 
        Header: 
          type: object
          properties: 
            Flow: 
              type: object
              properties: 
                FamilyID: 
                  type: integer
                  format: int32
                Version: 
                  type: integer
                  format: int32
                FlowID: 
                  type: integer
                  format: int32
                Name: 
                  type: string
            FlowInstanceID: 
              type: integer
              format: int32
            Status: 
              type: object
              properties: 
                ID: 
                  type: integer
                  format: int32
                Name: 
                  type: string
            Poster: 
              type: object
              properties: 
                Firstname: 
                  type: string
                Lastname: 
                  type: string
                Email: 
                  type: string
                ID: 
                  type: integer
                  format: int32
            Owner: 
              type: object
              properties: 
                Firstname: 
                  type: string
                Lastname: 
                  type: string
                Email: 
                  type: string
                ID: 
                  type: integer
                  format: int32
            Posted: 
              type: string
            FirstSubmitted: 
              type: string
            LastSubmitted: 
              type: string
        Values: 
          type: object
          properties: 
            InternalContactData: 
              type: object
              properties: 
                QueryID: 
                  type: integer
                  format: int32
                Name: 
                  type: string
                firstname: 
                  type: string
                lastname: 
                  type: string
                username: 
                  type: string
                email: 
                  type: string
                phone: 
                  type: string
                organization: 
                  type: string
            CaseType: 
              $ref: "#/components/schemas/FlowInstanceValue"
            ReferenceCode: 
              $ref: "#/components/schemas/FlowInstanceValue"
            AccessCardUser: 
              type: object
              properties: 
                QueryID: 
                  type: integer
                  format: int32
                Name: 
                  type: string
                firstname: 
                  type: string
                lastname: 
                  type: string
                username: 
                  type: string
                title: 
                  type: string
                organization: 
                  type: string
            Pincode: 
              type: object
              properties: 
                QueryID: 
                  type: integer
                  format: int32
                Name: 
                  type: string
                Number: 
                  type: string
            AccessCardNoPhoto: 
              $ref: "#/components/schemas/FlowInstanceValue"
            AccessCardPhoto: 
              type: object
              properties: 
                QueryID: 
                  type: integer
                  format: int32
                Name: 
                  type: string
                File: 
                  type: object
                  properties: 
                    ID: 
                      type: integer
                      format: int32
                    Name: 
                      type: string
                    Size: 
                      type: integer
                      format: int32
                    EncodedData: 
                      type: string
            AccessCardExtraInfo: 
              $ref: "#/components/schemas/FlowInstanceValue"
            AccessCardProperties: 
              $ref: "#/components/schemas/FlowInstanceValue"
            AccessCardShipTo: 
              $ref: "#/components/schemas/FlowInstanceValue"
            AccessCardSendsToAddress: 
              $ref: "#/components/schemas/FlowInstanceValue"
    FlowInstanceValue:
      type: object
      properties: 
        QueryID: 
          type: integer
          format: int32
        Name: 
          type: string
        Value: 
          type: string